apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-b
  template:
    metadata:
      labels:
        app: ecom-b
    spec:
      containers:
        - name: ecom-b
          image: kevingonzalez7997/d9_back_v1
          ports:
            - name: http
              containerPort: 8000